dist: bionic
sudo: required

jdk:
  - openjdk8
env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
    - ORACLE_BASE=/u01/app/oracle
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - PATH=$PATH:$ORACLE_HOME/jdbc/lib
    - DATABASE_VERSION=11.2.0.2
    - ORACLE_SID=XE
    - DATABASE_NAME=XE
    - ORA_SDTZ='Europe/London' #Needed as a client parameter
    - TZ='Europe/London'       #Needed as a DB Server parameter

before_install:
  - chmod +x .travis/oracle/download.sh
  - chmod +x .travis/oracle/install.sh
  - chmod +x .travis/setup_accounts.sh
  - 'gem install bundler || gem install bundler -v 1.17.3'

install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - .travis/setup_accounts.sh
  - bundle install --without=development

language: ruby
rvm:
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - 2.3.8
  - jruby-9.2.12.0
  - ruby-head
  - jruby-head

gemfile:
    - Gemfile
    - gemfiles/Gemfile.activerecord-5.0
    - gemfiles/Gemfile.activerecord-5.1
    - gemfiles/Gemfile.activerecord-5.2
    - gemfiles/Gemfile.activerecord-6.0
    - gemfiles/Gemfile.activerecord-master

matrix:
    exclude:
       - gemfile: gemfiles/Gemfile.activerecord-master
         rvm: 2.4.10
       - gemfile: gemfiles/Gemfile.activerecord-master
         rvm: 2.3.8
       - gemfile: gemfiles/Gemfile.activerecord-6.0
         rvm: 2.4.10
       - gemfile: gemfiles/Gemfile.activerecord-6.0
         rvm: 2.3.8
    allow_failures:
      - rvm: ruby-head
      - rvm: jruby-head
