name: RuboCop

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: /usr/lib/oracle/23/client64/lib

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
    - name: Install required package
      run: |
        sudo apt-get install alien
        sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
    - name: Download Oracle instant client
      run: |
        wget -q https://yum.oracle.com/repo/OracleLinux/OL8/oracle/instantclient23/x86_64/getPackage/oracle-instantclient-basic-23.26.1.0.0-1.el8.x86_64.rpm
        wget -q https://yum.oracle.com/repo/OracleLinux/OL8/oracle/instantclient23/x86_64/getPackage/oracle-instantclient-sqlplus-23.26.1.0.0-1.el8.x86_64.rpm
        wget -q https://yum.oracle.com/repo/OracleLinux/OL8/oracle/instantclient23/x86_64/getPackage/oracle-instantclient-devel-23.26.1.0.0-1.el8.x86_64.rpm
    - name: Install Oracle instant client
      run: |
        sudo alien -i oracle-instantclient-basic-23.26.1.0.0-1.el8.x86_64.rpm
        sudo alien -i oracle-instantclient-sqlplus-23.26.1.0.0-1.el8.x86_64.rpm
        sudo alien -i oracle-instantclient-devel-23.26.1.0.0-1.el8.x86_64.rpm

    - name: Build and run RuboCop
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rubocop --parallel
